WithMarks(StudentId) :-
    Marks(StudentId, CourseId, _),
    Courses(CourseId, CourseName),
    CourseName = :CourseName.
WithPlan(GroupId) :-
    Plan(GroupId, CourseId, _),
    Courses(CourseId, CourseName),
    CourseName = :CourseName.
res(StudentId, StudentName, GroupName) :-
    Students(StudentId, StudentName, GroupId),
    Groups(GroupId, GroupName),
    ¬ WithMarks(StudentId),
    WithPlan(GroupId).